### ISSUE TITLE
camera requirement.

### ISSUE THREAD

**Issue by kingchou007** [j96w/DexCap#10]
Hi,

I'm writing to ask about the sensor requirements for the task that uses 3D point cloud input for the DP policy.

Specifically, I'm wondering if the RealSense L515 sensor is necessary for this work, or if the D435 sensor could potentially be used as an alternative. The D435 seems to be a bit more widely available and potentially more cost-effective.

Thanks

**Comment by j96w** [comment]
Hi @kingchou007 , feel free to choose the sensor that best fits your needs. D435 also works. You may need to make some adjustments to the chest mount for the D435. Just remove the triangle plate (for L515), and you will find a screw hole from the bottom designed for the D435. You will also find two tiny bumps on the surface to stabilize the D435 along the screw axis.
<img width="814" alt="Screenshot 2024-07-10 at 9 35 19 AM" src="https://github.com/j96w/DexCap/assets/15310144/c5fa24ef-8463-4442-9aa7-a8d3efc2557b">
<img width="634" alt="Screenshot 2024-07-10 at 9 35 35 AM" src="https://github.com/j96w/DexCap/assets/15310144/01656518-a955-400e-a409-5290d68c2a89">
<img width="574" alt="Screenshot 2024-07-10 at 9 39 37 AM" src="https://github.com/j96w/DexCap/assets/15310144/ca50eb9c-f4a4-47f9-9a4c-3634a6754d62">

**Comment by j96w** [comment]
Hi @kingchou007 , we just released a [hardware update](https://docs.google.com/document/d/1ANxSA_PctkqFf3xqAkyktgBgDWEbrFK7b1OnJe54ltw/edit) with realsense D435 camera. Feel free to check it out.
