### ISSUE TITLE
How to use rokoko glove

### ISSUE THREAD

**Issue by xbkaishui** [j96w/DexCap#5]
Hi, I have some problem use rokoko glove capture data. I have config the custom live streaming and the port is 14041 protocol is json, 
when i use wireshark to sniff the network package, the response is not json, 

![image](https://github.com/j96w/DexCap/assets/1477791/0eac5269-bc9d-4f43-9a0d-927efd616214)

![image](https://github.com/j96w/DexCap/assets/1477791/2536c1c7-e1f7-4544-a173-28ebcb6820c0)

can you give some help. thanks

**Comment by j96w** [comment]
hi, you can check our [streaming code](https://github.com/j96w/DexCap/blob/main/STEP1_collect_data/redis_glove_server.py) for parsing the json with socket. In this code, we stream the glove readings to numpy and save them in redis-server for the robot workstation to access

**Comment by xbkaishui** [comment]
ok thanks
