### ISSUE TITLE
left_hand_joint_ori.txt data

### ISSUE THREAD

**Issue by LiYiquan9** [j96w/DexCap#9]
Thanks for the good work!

May I ask how you get the left_hand_joint_ori.txt data?

Thanks.

**Comment by j96w** [comment]
Hi, it is read from the glove, you can find the line of code from [glove streaming](https://github.com/j96w/DexCap/blob/3875f54d9b7265c08bccfd591bb07779dc346e63/STEP1_collect_data/redis_glove_server.py#L101) -> [data collection](https://github.com/j96w/DexCap/blob/3875f54d9b7265c08bccfd591bb07779dc346e63/STEP1_collect_data/data_recording.py#L261) -> [data saving](https://github.com/j96w/DexCap/blob/3875f54d9b7265c08bccfd591bb07779dc346e63/STEP1_collect_data/data_recording.py#L261).

**Comment by LiYiquan9** [comment]
Thanks！
